---
name: Build Fedora Kernel

# yamllint disable-line rule:truthy
on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "YamlLint"
        run: |
          docker run \
            --rm \
            -w /repo \
            -v $(pwd):/repo \
            -t \
            alpine:3.16 /bin/sh -c " \
              apk add --no-cache py-pip python3 bash \
              && pip3 install yamllint \
              && yamllint -s . \
            "
      - name: "ShellCheck"
        run: |
          docker run \
            --rm \
            -w /repo \
            -v $(pwd):/repo \
            -t \
            alpine:3.16 /bin/sh -c " \
              apk add --no-cache shellcheck bash \
              && shellcheck $(find . -type f -name "*.sh" |  tr '\n' ' ')
            "
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Remove unnecessary directories to free up space
        run: |
          sudo rm -rf /usr/local/.ghcup
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          sudo rm -rf /usr/local/lib/android/sdk/ndk
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/share/boost
      - name: "Build Fedora Kernel"
        timeout-minutes: 1200
        run: ./build_in_docker.sh
        env:
          RPM_SIGNING_KEY: ${{ secrets.RPM_SIGNING_KEY }}
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          draft: true
          files: |
            ./output_zip/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # You don't need to add this in secrets it's by default.
